BUTTON <ref *2> Button {
  _events: {
    newListener: [Function: fn],
    resize: [Function (anonymous)],
    attach: [Function (anonymous)],
    detach: [Function (anonymous)],
    keypress: [Function (anonymous)]
  },
  options: {
    autoFocus: false,
    position: {
      left: undefined,
      right: undefined,
      top: undefined,
      bottom: undefined,
      width: undefined,
      height: undefined
    },
    padding: {
      left: undefined,
      top: undefined,
      right: undefined,
      bottom: undefined
    }
  },
  screen: <ref *1> Screen {
    index: 0,
    program: Program {
      index: 0,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      options: [Object],
      input: [ReadStream],
      output: [WriteStream],
      zero: true,
      useBuffer: true,
      x: 0,
      y: 0,
      savedX: 0,
      savedY: 0,
      cols: 95,
      rows: 51,
      scrollTop: 0,
      scrollBottom: 50,
      _terminal: 'screen-256color',
      isOSXTerm: false,
      isiTerm2: false,
      isXFCE: false,
      isTerminator: false,
      isLXDE: false,
      isVTE: true,
      isRxvt: false,
      isXterm: false,
      tmux: true,
      tmuxVersion: 3,
      _buf: '\x1B[?1049h\x1B[?1h\x1B=\x1B[1;51r\x1B[?25l\x1B[1;1H\x1B[H\x1B[2J',
      _flush: [Function: bound ],
      _tputSetup: true,
      tput: [Tput],
      put: [Function],
      padding: undefined,
      extended: undefined,
      printf: undefined,
      termcap: undefined,
      error: Error: Terminfo not found.
          at Tput.setup (/home/zmg/Tinker/wiener/node_modules/blessed/lib/tput.js:91:18)
          at new Tput (/home/zmg/Tinker/wiener/node_modules/blessed/lib/tput.js:63:10)
          at Program.setupTput (/home/zmg/Tinker/wiener/node_modules/blessed/lib/program.js:251:26)
          at new Program (/home/zmg/Tinker/wiener/node_modules/blessed/lib/program.js:112:10)
          at Program (/home/zmg/Tinker/wiener/node_modules/blessed/lib/program.js:31:12)
          at new Screen (/home/zmg/Tinker/wiener/node_modules/blessed/lib/widgets/screen.js:49:20)
          at Function.Screen (/home/zmg/Tinker/wiener/node_modules/blessed/lib/widgets/screen.js:36:12)
          at REPL4:1:24
          at Script.runInThisContext (vm.js:134:12)
          at REPLServer.defaultEval (repl.js:566:29),
      terminfoPrefix: undefined,
      terminfoFile: undefined,
      termcapFile: undefined,
      auto_left_margin: false,
      auto_right_margin: true,
      no_esc_ctlc: false,
      ceol_standout_glitch: false,
      eat_newline_glitch: true,
      erase_overstrike: false,
      generic_type: false,
      hard_copy: false,
      has_meta_key: true,
      has_status_line: false,
      insert_null_glitch: false,
      memory_above: false,
      memory_below: false,
      move_insert_mode: true,
      move_standout_mode: true,
      over_strike: false,
      status_line_esc_ok: false,
      dest_tabs_magic_smso: false,
      tilde_glitch: false,
      transparent_underline: false,
      xon_xoff: false,
      needs_xon_xoff: false,
      prtr_silent: true,
      hard_cursor: false,
      non_rev_rmcup: false,
      no_pad_char: true,
      non_dest_scroll_region: false,
      can_change: false,
      back_color_erase: true,
      hue_lightness_saturation: false,
      col_addr_glitch: false,
      cr_cancels_micro_mode: false,
      has_print_wheel: false,
      row_addr_glitch: false,
      semi_auto_right_margin: false,
      cpi_changes_res: false,
      lpi_changes_res: false,
      backspaces_with_bs: true,
      AX: true,
      XT: true,
      columns: 80,
      init_tabs: 8,
      lines: 24,
      lines_of_memory: -1,
      magic_cookie_glitch: -1,
      padding_baud_rate: -1,
      virtual_terminal: -1,
      width_status_line: -1,
      num_labels: -1,
      label_height: -1,
      label_width: -1,
      max_attributes: -1,
      maximum_windows: -1,
      max_colors: 8,
      max_pairs: 64,
      back_tab: [Function (anonymous)],
      carriage_return: [Function (anonymous)],
      change_scroll_region: [Function (anonymous)],
      clear_all_tabs: [Function (anonymous)],
      clear_screen: [Function (anonymous)],
      clr_eol: [Function (anonymous)],
      clr_eos: [Function (anonymous)],
      column_address: [Function (anonymous)],
      cursor_address: [Function (anonymous)],
      cursor_down: [Function (anonymous)],
      cursor_home: [Function (anonymous)],
      cursor_left: [Function (anonymous)],
      cursor_normal: [Function (anonymous)],
      cursor_right: [Function (anonymous)],
      cursor_up: [Function (anonymous)],
      cursor_visible: [Function (anonymous)],
      delete_character: [Function (anonymous)],
      delete_line: [Function (anonymous)],
      enter_blink_mode: [Function (anonymous)],
      enter_bold_mode: [Function (anonymous)],
      enter_ca_mode: [Function (anonymous)],
      enter_insert_mode: [Function (anonymous)],
      enter_secure_mode: [Function (anonymous)],
      enter_reverse_mode: [Function (anonymous)],
      enter_standout_mode: [Function (anonymous)],
      enter_underline_mode: [Function (anonymous)],
      erase_chars: [Function (anonymous)],
      exit_attribute_mode: [Function (anonymous)],
      exit_ca_mode: [Function (anonymous)],
      exit_insert_mode: [Function (anonymous)],
      exit_standout_mode: [Function (anonymous)],
      exit_underline_mode: [Function (anonymous)],
      flash_screen: [Function (anonymous)],
      init_2string: [Function (anonymous)],
      insert_line: [Function (anonymous)],
      key_backspace: [Function (anonymous)],
      key_dc: [Function (anonymous)],
      key_down: [Function (anonymous)],
      key_f1: [Function (anonymous)],
      key_f10: [Function (anonymous)],
      key_f2: [Function (anonymous)],
      key_f3: [Function (anonymous)],
      key_f4: [Function (anonymous)],
      key_f5: [Function (anonymous)],
      key_f6: [Function (anonymous)],
      key_f7: [Function (anonymous)],
      key_f8: [Function (anonymous)],
      key_f9: [Function (anonymous)],
      key_home: [Function (anonymous)],
      key_ic: [Function (anonymous)],
      key_left: [Function (anonymous)],
      key_npage: [Function (anonymous)],
      key_ppage: [Function (anonymous)],
      key_right: [Function (anonymous)],
      key_sf: [Function (anonymous)],
      key_sr: [Function (anonymous)],
      key_up: [Function (anonymous)],
      keypad_local: [Function (anonymous)],
      keypad_xmit: [Function (anonymous)],
      meta_off: [Function (anonymous)],
      meta_on: [Function (anonymous)],
      parm_dch: [Function (anonymous)],
      parm_delete_line: [Function (anonymous)],
      parm_down_cursor: [Function (anonymous)],
      parm_ich: [Function (anonymous)],
      parm_index: [Function (anonymous)],
      parm_insert_line: [Function (anonymous)],
      parm_left_cursor: [Function (anonymous)],
      parm_right_cursor: [Function (anonymous)],
      parm_rindex: [Function (anonymous)],
      parm_up_cursor: [Function (anonymous)],
      reset_1string: [Function (anonymous)],
      reset_2string: [Function (anonymous)],
      restore_cursor: [Function (anonymous)],
      row_address: [Function (anonymous)],
      save_cursor: [Function (anonymous)],
      scroll_forward: [Function (anonymous)],
      scroll_reverse: [Function (anonymous)],
      set_attributes: [Function (anonymous)],
      set_tab: [Function (anonymous)],
      key_b2: [Function (anonymous)],
      acs_chars: [Function (anonymous)],
      key_btab: [Function (anonymous)],
      enter_am_mode: [Function (anonymous)],
      exit_am_mode: [Function (anonymous)],
      key_end: [Function (anonymous)],
      key_enter: [Function (anonymous)],
      key_sdc: [Function (anonymous)],
      key_send: [Function (anonymous)],
      key_shome: [Function (anonymous)],
      key_sic: [Function (anonymous)],
      key_sleft: [Function (anonymous)],
      key_snext: [Function (anonymous)],
      key_sprevious: [Function (anonymous)],
      key_sright: [Function (anonymous)],
      key_f11: [Function (anonymous)],
      key_f12: [Function (anonymous)],
      key_f13: [Function (anonymous)],
      key_f14: [Function (anonymous)],
      key_f15: [Function (anonymous)],
      key_f16: [Function (anonymous)],
      key_f17: [Function (anonymous)],
      key_f18: [Function (anonymous)],
      key_f19: [Function (anonymous)],
      key_f20: [Function (anonymous)],
      key_f21: [Function (anonymous)],
      key_f22: [Function (anonymous)],
      key_f23: [Function (anonymous)],
      key_f24: [Function (anonymous)],
      key_f25: [Function (anonymous)],
      key_f26: [Function (anonymous)],
      key_f27: [Function (anonymous)],
      key_f28: [Function (anonymous)],
      key_f29: [Function (anonymous)],
      key_f30: [Function (anonymous)],
      key_f31: [Function (anonymous)],
      key_f32: [Function (anonymous)],
      key_f33: [Function (anonymous)],
      key_f34: [Function (anonymous)],
      key_f35: [Function (anonymous)],
      key_f36: [Function (anonymous)],
      key_f37: [Function (anonymous)],
      key_f38: [Function (anonymous)],
      key_f39: [Function (anonymous)],
      key_f40: [Function (anonymous)],
      key_f41: [Function (anonymous)],
      key_f42: [Function (anonymous)],
      key_f43: [Function (anonymous)],
      key_f44: [Function (anonymous)],
      key_f45: [Function (anonymous)],
      key_f46: [Function (anonymous)],
      key_f47: [Function (anonymous)],
      key_f48: [Function (anonymous)],
      key_f49: [Function (anonymous)],
      key_f50: [Function (anonymous)],
      key_f51: [Function (anonymous)],
      key_f52: [Function (anonymous)],
      key_f53: [Function (anonymous)],
      key_f54: [Function (anonymous)],
      key_f55: [Function (anonymous)],
      key_f56: [Function (anonymous)],
      key_f57: [Function (anonymous)],
      key_f58: [Function (anonymous)],
      key_f59: [Function (anonymous)],
      key_f60: [Function (anonymous)],
      key_f61: [Function (anonymous)],
      key_f62: [Function (anonymous)],
      key_f63: [Function (anonymous)],
      clr_bol: [Function (anonymous)],
      user6: [Function (anonymous)],
      user7: [Function (anonymous)],
      user8: [Function (anonymous)],
      user9: [Function (anonymous)],
      orig_pair: [Function (anonymous)],
      set_foreground: [Function (anonymous)],
      set_background: [Function (anonymous)],
      key_mouse: [Function (anonymous)],
      set_a_foreground: [Function (anonymous)],
      set_a_background: [Function (anonymous)],
      memory_lock: [Function (anonymous)],
      memory_unlock: [Function (anonymous)],
      Cr: [Function (anonymous)],
      Cs: [Function (anonymous)],
      E3: [Function (anonymous)],
      Ms: [Function (anonymous)],
      Se: [Function (anonymous)],
      Ss: [Function (anonymous)],
      kDC3: [Function (anonymous)],
      kDC4: [Function (anonymous)],
      kDC5: [Function (anonymous)],
      kDC6: [Function (anonymous)],
      kDC7: [Function (anonymous)],
      kDN: [Function (anonymous)],
      kDN3: [Function (anonymous)],
      kDN4: [Function (anonymous)],
      kDN5: [Function (anonymous)],
      kDN6: [Function (anonymous)],
      kDN7: [Function (anonymous)],
      kEND3: [Function (anonymous)],
      kEND4: [Function (anonymous)],
      kEND5: [Function (anonymous)],
      kEND6: [Function (anonymous)],
      kEND7: [Function (anonymous)],
      kHOM3: [Function (anonymous)],
      kHOM4: [Function (anonymous)],
      kHOM5: [Function (anonymous)],
      kHOM6: [Function (anonymous)],
      kHOM7: [Function (anonymous)],
      kIC3: [Function (anonymous)],
      kIC4: [Function (anonymous)],
      kIC5: [Function (anonymous)],
      kIC6: [Function (anonymous)],
      kIC7: [Function (anonymous)],
      kLFT3: [Function (anonymous)],
      kLFT4: [Function (anonymous)],
      kLFT5: [Function (anonymous)],
      kLFT6: [Function (anonymous)],
      kLFT7: [Function (anonymous)],
      kNXT3: [Function (anonymous)],
      kNXT4: [Function (anonymous)],
      kNXT5: [Function (anonymous)],
      kNXT6: [Function (anonymous)],
      kNXT7: [Function (anonymous)],
      kPRV3: [Function (anonymous)],
      kPRV4: [Function (anonymous)],
      kPRV5: [Function (anonymous)],
      kPRV6: [Function (anonymous)],
      kPRV7: [Function (anonymous)],
      kRIT3: [Function (anonymous)],
      kRIT4: [Function (anonymous)],
      kRIT5: [Function (anonymous)],
      kRIT6: [Function (anonymous)],
      kRIT7: [Function (anonymous)],
      kUP: [Function (anonymous)],
      kUP3: [Function (anonymous)],
      kUP4: [Function (anonymous)],
      kUP5: [Function (anonymous)],
      kUP6: [Function (anonymous)],
      kUP7: [Function (anonymous)],
      ka2: [Function (anonymous)],
      kb1: [Function (anonymous)],
      kb3: [Function (anonymous)],
      kc2: [Function (anonymous)],
      crt_no_scrolling: false,
      no_correctly_working_cr: false,
      gnu_has_meta_key: false,
      linefeed_is_newline: false,
      has_hardware_tabs: false,
      return_does_clr_eol: false,
      no_color_video: -1,
      buffer_capacity: -1,
      dot_vert_spacing: -1,
      dot_horz_spacing: -1,
      max_micro_address: -1,
      max_micro_jump: -1,
      micro_col_size: -1,
      micro_line_size: -1,
      number_of_pins: -1,
      output_res_char: -1,
      output_res_line: -1,
      output_res_horz_inch: -1,
      output_res_vert_inch: -1,
      print_rate: -1,
      wide_char_size: -1,
      buttons: -1,
      bit_image_entwining: -1,
      bit_image_type: -1,
      magic_cookie_glitch_ul: -1,
      carriage_return_delay: -1,
      new_line_delay: -1,
      backspace_delay: -1,
      horizontal_tab_delay: -1,
      number_of_function_keys: -1,
      command_character: [Function (anonymous)],
      cursor_mem_address: [Function (anonymous)],
      cursor_to_ll: [Function (anonymous)],
      dis_status_line: [Function (anonymous)],
      down_half_line: [Function (anonymous)],
      enter_delete_mode: [Function (anonymous)],
      enter_dim_mode: [Function (anonymous)],
      enter_protected_mode: [Function (anonymous)],
      exit_delete_mode: [Function (anonymous)],
      form_feed: [Function (anonymous)],
      from_status_line: [Function (anonymous)],
      init_1string: [Function (anonymous)],
      init_3string: [Function (anonymous)],
      init_file: [Function (anonymous)],
      insert_character: [Function (anonymous)],
      insert_padding: [Function (anonymous)],
      key_catab: [Function (anonymous)],
      key_clear: [Function (anonymous)],
      key_ctab: [Function (anonymous)],
      key_dl: [Function (anonymous)],
      key_eic: [Function (anonymous)],
      key_eol: [Function (anonymous)],
      key_eos: [Function (anonymous)],
      key_f0: [Function (anonymous)],
      key_il: [Function (anonymous)],
      key_ll: [Function (anonymous)],
      key_stab: [Function (anonymous)],
      lab_f0: [Function (anonymous)],
      lab_f1: [Function (anonymous)],
      lab_f10: [Function (anonymous)],
      lab_f2: [Function (anonymous)],
      lab_f3: [Function (anonymous)],
      lab_f4: [Function (anonymous)],
      lab_f5: [Function (anonymous)],
      lab_f6: [Function (anonymous)],
      lab_f7: [Function (anonymous)],
      lab_f8: [Function (anonymous)],
      lab_f9: [Function (anonymous)],
      pad_char: [Function (anonymous)],
      pkey_key: [Function (anonymous)],
      pkey_local: [Function (anonymous)],
      pkey_xmit: [Function (anonymous)],
      repeat_char: [Function (anonymous)],
      reset_3string: [Function (anonymous)],
      reset_file: [Function (anonymous)],
      set_window: [Function (anonymous)],
      to_status_line: [Function (anonymous)],
      underline_char: [Function (anonymous)],
      up_half_line: [Function (anonymous)],
      init_prog: [Function (anonymous)],
      key_a1: [Function (anonymous)],
      key_a3: [Function (anonymous)],
      key_c1: [Function (anonymous)],
      key_c3: [Function (anonymous)],
      char_padding: [Function (anonymous)],
      plab_norm: [Function (anonymous)],
      enter_xon_mode: [Function (anonymous)],
      exit_xon_mode: [Function (anonymous)],
      xon_character: [Function (anonymous)],
      xoff_character: [Function (anonymous)],
      ena_acs: [Function (anonymous)],
      label_on: [Function (anonymous)],
      label_off: [Function (anonymous)],
      key_beg: [Function (anonymous)],
      key_cancel: [Function (anonymous)],
      key_close: [Function (anonymous)],
      key_command: [Function (anonymous)],
      key_copy: [Function (anonymous)],
      key_create: [Function (anonymous)],
      key_exit: [Function (anonymous)],
      key_find: [Function (anonymous)],
      key_help: [Function (anonymous)],
      key_mark: [Function (anonymous)],
      key_message: [Function (anonymous)],
      key_move: [Function (anonymous)],
      key_next: [Function (anonymous)],
      key_open: [Function (anonymous)],
      key_options: [Function (anonymous)],
      key_previous: [Function (anonymous)],
      key_print: [Function (anonymous)],
      key_redo: [Function (anonymous)],
      key_reference: [Function (anonymous)],
      key_refresh: [Function (anonymous)],
      key_replace: [Function (anonymous)],
      key_restart: [Function (anonymous)],
      key_resume: [Function (anonymous)],
      key_save: [Function (anonymous)],
      key_suspend: [Function (anonymous)],
      key_undo: [Function (anonymous)],
      key_sbeg: [Function (anonymous)],
      key_scancel: [Function (anonymous)],
      key_scommand: [Function (anonymous)],
      key_scopy: [Function (anonymous)],
      key_screate: [Function (anonymous)],
      key_sdl: [Function (anonymous)],
      key_select: [Function (anonymous)],
      key_seol: [Function (anonymous)],
      key_sexit: [Function (anonymous)],
      key_sfind: [Function (anonymous)],
      key_shelp: [Function (anonymous)],
      key_smessage: [Function (anonymous)],
      key_smove: [Function (anonymous)],
      key_soptions: [Function (anonymous)],
      key_sprint: [Function (anonymous)],
      key_sredo: [Function (anonymous)],
      key_sreplace: [Function (anonymous)],
      key_srsume: [Function (anonymous)],
      key_ssave: [Function (anonymous)],
      key_ssuspend: [Function (anonymous)],
      key_sundo: [Function (anonymous)],
      req_for_input: [Function (anonymous)],
      clear_margins: [Function (anonymous)],
      set_left_margin: [Function (anonymous)],
      set_right_margin: [Function (anonymous)],
      label_format: [Function (anonymous)],
      set_clock: [Function (anonymous)],
      display_clock: [Function (anonymous)],
      remove_clock: [Function (anonymous)],
      create_window: [Function (anonymous)],
      goto_window: [Function (anonymous)],
      hangup: [Function (anonymous)],
      dial_phone: [Function (anonymous)],
      quick_dial: [Function (anonymous)],
      tone: [Function (anonymous)],
      pulse: [Function (anonymous)],
      flash_hook: [Function (anonymous)],
      fixed_pause: [Function (anonymous)],
      wait_tone: [Function (anonymous)],
      user0: [Function (anonymous)],
      user1: [Function (anonymous)],
      user2: [Function (anonymous)],
      user3: [Function (anonymous)],
      user4: [Function (anonymous)],
      user5: [Function (anonymous)],
      orig_colors: [Function (anonymous)],
      initialize_color: [Function (anonymous)],
      initialize_pair: [Function (anonymous)],
      set_color_pair: [Function (anonymous)],
      change_char_pitch: [Function (anonymous)],
      change_line_pitch: [Function (anonymous)],
      change_res_horz: [Function (anonymous)],
      change_res_vert: [Function (anonymous)],
      define_char: [Function (anonymous)],
      enter_doublewide_mode: [Function (anonymous)],
      enter_draft_quality: [Function (anonymous)],
      enter_italics_mode: [Function (anonymous)],
      enter_leftward_mode: [Function (anonymous)],
      enter_micro_mode: [Function (anonymous)],
      enter_near_letter_quality: [Function (anonymous)],
      enter_normal_quality: [Function (anonymous)],
      enter_shadow_mode: [Function (anonymous)],
      enter_subscript_mode: [Function (anonymous)],
      enter_superscript_mode: [Function (anonymous)],
      enter_upward_mode: [Function (anonymous)],
      exit_doublewide_mode: [Function (anonymous)],
      exit_italics_mode: [Function (anonymous)],
      exit_leftward_mode: [Function (anonymous)],
      exit_micro_mode: [Function (anonymous)],
      exit_shadow_mode: [Function (anonymous)],
      exit_subscript_mode: [Function (anonymous)],
      exit_superscript_mode: [Function (anonymous)],
      exit_upward_mode: [Function (anonymous)],
      micro_column_address: [Function (anonymous)],
      micro_down: [Function (anonymous)],
      micro_left: [Function (anonymous)],
      micro_right: [Function (anonymous)],
      micro_row_address: [Function (anonymous)],
      micro_up: [Function (anonymous)],
      order_of_pins: [Function (anonymous)],
      parm_down_micro: [Function (anonymous)],
      parm_left_micro: [Function (anonymous)],
      parm_right_micro: [Function (anonymous)],
      parm_up_micro: [Function (anonymous)],
      select_char_set: [Function (anonymous)],
      set_bottom_margin: [Function (anonymous)],
      set_bottom_margin_parm: [Function (anonymous)],
      set_left_margin_parm: [Function (anonymous)],
      set_right_margin_parm: [Function (anonymous)],
      set_top_margin: [Function (anonymous)],
      set_top_margin_parm: [Function (anonymous)],
      start_bit_image: [Function (anonymous)],
      start_char_set_def: [Function (anonymous)],
      stop_bit_image: [Function (anonymous)],
      stop_char_set_def: [Function (anonymous)],
      subscript_characters: [Function (anonymous)],
      superscript_characters: [Function (anonymous)],
      these_cause_cr: [Function (anonymous)],
      zero_motion: [Function (anonymous)],
      char_set_names: [Function (anonymous)],
      mouse_info: [Function (anonymous)],
      get_mouse: [Function (anonymous)],
      pkey_plab: [Function (anonymous)],
      device_type: [Function (anonymous)],
      code_set_init: [Function (anonymous)],
      set0_des_seq: [Function (anonymous)],
      set1_des_seq: [Function (anonymous)],
      set2_des_seq: [Function (anonymous)],
      set3_des_seq: [Function (anonymous)],
      set_lr_margin: [Function (anonymous)],
      set_tb_margin: [Function (anonymous)],
      bit_image_repeat: [Function (anonymous)],
      bit_image_newline: [Function (anonymous)],
      bit_image_carriage_return: [Function (anonymous)],
      color_names: [Function (anonymous)],
      define_bit_image_region: [Function (anonymous)],
      end_bit_image_region: [Function (anonymous)],
      set_color_band: [Function (anonymous)],
      set_page_length: [Function (anonymous)],
      display_pc_char: [Function (anonymous)],
      enter_pc_charset_mode: [Function (anonymous)],
      exit_pc_charset_mode: [Function (anonymous)],
      enter_scancode_mode: [Function (anonymous)],
      exit_scancode_mode: [Function (anonymous)],
      pc_term_options: [Function (anonymous)],
      scancode_escape: [Function (anonymous)],
      alt_scancode_esc: [Function (anonymous)],
      enter_horizontal_hl_mode: [Function (anonymous)],
      enter_left_hl_mode: [Function (anonymous)],
      enter_low_hl_mode: [Function (anonymous)],
      enter_right_hl_mode: [Function (anonymous)],
      enter_top_hl_mode: [Function (anonymous)],
      enter_vertical_hl_mode: [Function (anonymous)],
      set_a_attributes: [Function (anonymous)],
      set_pglen_inch: [Function (anonymous)],
      termcap_init2: [Function (anonymous)],
      termcap_reset: [Function (anonymous)],
      linefeed_if_not_lf: [Function (anonymous)],
      backspace_if_not_bs: [Function (anonymous)],
      other_non_function_keys: [Function (anonymous)],
      arrow_key_map: [Function (anonymous)],
      acs_ulcorner: [Function (anonymous)],
      acs_llcorner: [Function (anonymous)],
      acs_urcorner: [Function (anonymous)],
      acs_lrcorner: [Function (anonymous)],
      acs_ltee: [Function (anonymous)],
      acs_rtee: [Function (anonymous)],
      acs_btee: [Function (anonymous)],
      acs_ttee: [Function (anonymous)],
      acs_hline: [Function (anonymous)],
      acs_vline: [Function (anonymous)],
      acs_plus: [Function (anonymous)],
      box_chars_1: [Function (anonymous)],
      bw: false,
      am: true,
      xsb: false,
      beehive_glitch: false,
      xhp: false,
      xenl: true,
      eo: false,
      gn: false,
      hc: false,
      km: true,
      hs: false,
      in: false,
      db: false,
      mir: true,
      msgr: true,
      os: false,
      eslok: false,
      xt: false,
      teleray_glitch: false,
      hz: false,
      ul: false,
      xon: false,
      nxon: false,
      mc5i: true,
      chts: false,
      nrrmc: false,
      npc: true,
      ndscr: false,
      ccc: false,
      bce: true,
      hls: false,
      xhpa: false,
      crxm: false,
      daisy: false,
      xvpa: false,
      sam: false,
      cpix: false,
      lpix: false,
      it: 8,
      lm: -1,
      xmc: -1,
      pb: -1,
      vt: -1,
      wsl: -1,
      nlab: -1,
      lh: -1,
      lw: -1,
      ma: -1,
      wnum: -1,
      colors: 8,
      pairs: 64,
      cud1: [Function (anonymous)],
      home: [Function (anonymous)],
      cub1: [Function (anonymous)],
      cuf1: [Function (anonymous)],
      cuu1: [Function (anonymous)],
      dch1: [Function (anonymous)],
      dl1: [Function (anonymous)],
      blink: [Function (anonymous)],
      bold: [Function (anonymous)],
      smir: [Function (anonymous)],
      invis: [Function (anonymous)],
      rev: [Function (anonymous)],
      smso: [Function (anonymous)],
      smul: [Function (anonymous)],
      sgr0: [Function (anonymous)],
      rmir: [Function (anonymous)],
      rmso: [Function (anonymous)],
      rmul: [Function (anonymous)],
      flash: [Function (anonymous)],
      is2: [Function (anonymous)],
      il1: [Function (anonymous)],
      kdch1: [Function (anonymous)],
      kcud1: [Function (anonymous)],
      kf1: [Function (anonymous)],
      kf10: [Function (anonymous)],
      kf2: [Function (anonymous)],
      kf3: [Function (anonymous)],
      kf4: [Function (anonymous)],
      kf5: [Function (anonymous)],
      kf6: [Function (anonymous)],
      kf7: [Function (anonymous)],
      kf8: [Function (anonymous)],
      kf9: [Function (anonymous)],
      khome: [Function (anonymous)],
      kich1: [Function (anonymous)],
      kcub1: [Function (anonymous)],
      knp: [Function (anonymous)],
      kpp: [Function (anonymous)],
      kcuf1: [Function (anonymous)],
      kind: [Function (anonymous)],
      kri: [Function (anonymous)],
      kcuu1: [Function (anonymous)],
      rmkx: [Function (anonymous)],
      smkx: [Function (anonymous)],
      rmm: [Function (anonymous)],
      smm: [Function (anonymous)],
      indn: [Function (anonymous)],
      rin: [Function (anonymous)],
      rs1: [Function (anonymous)],
      hts: [Function (anonymous)],
      kb2: [Function (anonymous)],
      acsc: [Object],
      kcbt: [Function (anonymous)],
      smam: [Function (anonymous)],
      rmam: [Function (anonymous)],
      kend: [Function (anonymous)],
      kent: [Function (anonymous)],
      kDC: [Function (anonymous)],
      kEND: [Function (anonymous)],
      kHOM: [Function (anonymous)],
      kIC: [Function (anonymous)],
      kLFT: [Function (anonymous)],
      kNXT: [Function (anonymous)],
      kPRV: [Function (anonymous)],
      kRIT: [Function (anonymous)],
      kf11: [Function (anonymous)],
      kf12: [Function (anonymous)],
      kf13: [Function (anonymous)],
      kf14: [Function (anonymous)],
      kf15: [Function (anonymous)],
      kf16: [Function (anonymous)],
      kf17: [Function (anonymous)],
      kf18: [Function (anonymous)],
      kf19: [Function (anonymous)],
      kf20: [Function (anonymous)],
      kf21: [Function (anonymous)],
      kf22: [Function (anonymous)],
      kf23: [Function (anonymous)],
      kf24: [Function (anonymous)],
      kf25: [Function (anonymous)],
      kf26: [Function (anonymous)],
      kf27: [Function (anonymous)],
      kf28: [Function (anonymous)],
      kf29: [Function (anonymous)],
      kf30: [Function (anonymous)],
      kf31: [Function (anonymous)],
      kf32: [Function (anonymous)],
      kf33: [Function (anonymous)],
      kf34: [Function (anonymous)],
      kf35: [Function (anonymous)],
      kf36: [Function (anonymous)],
      kf37: [Function (anonymous)],
      kf38: [Function (anonymous)],
      kf39: [Function (anonymous)],
      kf40: [Function (anonymous)],
      kf41: [Function (anonymous)],
      kf42: [Function (anonymous)],
      kf43: [Function (anonymous)],
      kf44: [Function (anonymous)],
      kf45: [Function (anonymous)],
      kf46: [Function (anonymous)],
      kf47: [Function (anonymous)],
      kf48: [Function (anonymous)],
      kf49: [Function (anonymous)],
      kf50: [Function (anonymous)],
      kf51: [Function (anonymous)],
      kf52: [Function (anonymous)],
      kf53: [Function (anonymous)],
      kf54: [Function (anonymous)],
      kf55: [Function (anonymous)],
      kf56: [Function (anonymous)],
      kf57: [Function (anonymous)],
      kf58: [Function (anonymous)],
      kf59: [Function (anonymous)],
      kf60: [Function (anonymous)],
      kf61: [Function (anonymous)],
      kf62: [Function (anonymous)],
      kf63: [Function (anonymous)],
      el1: [Function (anonymous)],
      u6: [Function (anonymous)],
      u7: [Function (anonymous)],
      u8: [Function (anonymous)],
      u9: [Function (anonymous)],
      op: [Function (anonymous)],
      setf: [Function (anonymous)],
      setb: [Function (anonymous)],
      kmous: [Function (anonymous)],
      setaf: [Function (anonymous)],
      setab: [Function (anonymous)],
      ncv: -1,
      bufsz: -1,
      spinv: -1,
      spinh: -1,
      maddr: -1,
      mjump: -1,
      mcs: -1,
      micro_char_size: -1,
      mls: -1,
      npins: -1,
      orc: -1,
      orl: -1,
      orhi: -1,
      orvi: -1,
      cps: -1,
      widcs: -1,
      btns: -1,
      bitwin: -1,
      bitype: -1,
      cmdch: [Function (anonymous)],
      mrcup: [Function (anonymous)],
      ll: [Function (anonymous)],
      dsl: [Function (anonymous)],
      hd: [Function (anonymous)],
      smdc: [Function (anonymous)],
      dim: [Function (anonymous)],
      prot: [Function (anonymous)],
      rmdc: [Function (anonymous)],
      fsl: [Function (anonymous)],
      is1: [Function (anonymous)],
      is3: [Function (anonymous)],
      if: [Function (anonymous)],
      ich1: [Function (anonymous)],
      ip: [Function (anonymous)],
      ktbc: [Function (anonymous)],
      kclr: [Function (anonymous)],
      kctab: [Function (anonymous)],
      kdl1: [Function (anonymous)],
      krmir: [Function (anonymous)],
      kel: [Function (anonymous)],
      ked: [Function (anonymous)],
      kf0: [Function (anonymous)],
      kil1: [Function (anonymous)],
      kll: [Function (anonymous)],
      khts: [Function (anonymous)],
      lf0: [Function (anonymous)],
      lf1: [Function (anonymous)],
      lf10: [Function (anonymous)],
      lf2: [Function (anonymous)],
      lf3: [Function (anonymous)],
      lf4: [Function (anonymous)],
      lf5: [Function (anonymous)],
      lf6: [Function (anonymous)],
      lf7: [Function (anonymous)],
      lf8: [Function (anonymous)],
      lf9: [Function (anonymous)],
      pad: [Function (anonymous)],
      pfkey: [Function (anonymous)],
      pfloc: [Function (anonymous)],
      pfx: [Function (anonymous)],
      rs3: [Function (anonymous)],
      rf: [Function (anonymous)],
      wind: [Function (anonymous)],
      tsl: [Function (anonymous)],
      uc: [Function (anonymous)],
      hu: [Function (anonymous)],
      iprog: [Function (anonymous)],
      ka1: [Function (anonymous)],
      ka3: [Function (anonymous)],
      kc1: [Function (anonymous)],
      kc3: [Function (anonymous)],
      rmp: [Function (anonymous)],
      pln: [Function (anonymous)],
      smxon: [Function (anonymous)],
      rmxon: [Function (anonymous)],
      xonc: [Function (anonymous)],
      xoffc: [Function (anonymous)],
      enacs: [Function (anonymous)],
      smln: [Function (anonymous)],
      rmln: [Function (anonymous)],
      kbeg: [Function (anonymous)],
      kcan: [Function (anonymous)],
      kclo: [Function (anonymous)],
      kcmd: [Function (anonymous)],
      kcpy: [Function (anonymous)],
      kcrt: [Function (anonymous)],
      kext: [Function (anonymous)],
      kfnd: [Function (anonymous)],
      khlp: [Function (anonymous)],
      kmrk: [Function (anonymous)],
      kmsg: [Function (anonymous)],
      kmov: [Function (anonymous)],
      knxt: [Function (anonymous)],
      kopn: [Function (anonymous)],
      kopt: [Function (anonymous)],
      kprv: [Function (anonymous)],
      kprt: [Function (anonymous)],
      krdo: [Function (anonymous)],
      kref: [Function (anonymous)],
      krfr: [Function (anonymous)],
      krpl: [Function (anonymous)],
      krst: [Function (anonymous)],
      kres: [Function (anonymous)],
      ksav: [Function (anonymous)],
      kspd: [Function (anonymous)],
      kund: [Function (anonymous)],
      kBEG: [Function (anonymous)],
      kCAN: [Function (anonymous)],
      kCMD: [Function (anonymous)],
      kCPY: [Function (anonymous)],
      kCRT: [Function (anonymous)],
      kDL: [Function (anonymous)],
      kslt: [Function (anonymous)],
      kEOL: [Function (anonymous)],
      kEXT: [Function (anonymous)],
      kFND: [Function (anonymous)],
      kHLP: [Function (anonymous)],
      kMSG: [Function (anonymous)],
      kMOV: [Function (anonymous)],
      kOPT: [Function (anonymous)],
      kPRT: [Function (anonymous)],
      kRDO: [Function (anonymous)],
      kRPL: [Function (anonymous)],
      kRES: [Function (anonymous)],
      kSAV: [Function (anonymous)],
      kSPD: [Function (anonymous)],
      kUND: [Function (anonymous)],
      rfi: [Function (anonymous)],
      mgc: [Function (anonymous)],
      smgl: [Function (anonymous)],
      smgr: [Function (anonymous)],
      fln: [Function (anonymous)],
      sclk: [Function (anonymous)],
      dclk: [Function (anonymous)],
      rmclk: [Function (anonymous)],
      cwin: [Function (anonymous)],
      wingo: [Function (anonymous)],
      hup: [Function (anonymous)],
      dial: [Function (anonymous)],
      qdial: [Function (anonymous)],
      hook: [Function (anonymous)],
      wait: [Function (anonymous)],
      u0: [Function (anonymous)],
      u1: [Function (anonymous)],
      u2: [Function (anonymous)],
      u3: [Function (anonymous)],
      u4: [Function (anonymous)],
      u5: [Function (anonymous)],
      oc: [Function (anonymous)],
      initc: [Function (anonymous)],
      initp: [Function (anonymous)],
      scp: [Function (anonymous)],
      cpi: [Function (anonymous)],
      lpi: [Function (anonymous)],
      chr: [Function (anonymous)],
      cvr: [Function (anonymous)],
      defc: [Function (anonymous)],
      swidm: [Function (anonymous)],
      sdrfq: [Function (anonymous)],
      sitm: [Function (anonymous)],
      slm: [Function (anonymous)],
      smicm: [Function (anonymous)],
      snlq: [Function (anonymous)],
      snrmq: [Function (anonymous)],
      sshm: [Function (anonymous)],
      ssubm: [Function (anonymous)],
      ssupm: [Function (anonymous)],
      sum: [Function (anonymous)],
      rwidm: [Function (anonymous)],
      ritm: [Function (anonymous)],
      rlm: [Function (anonymous)],
      rmicm: [Function (anonymous)],
      rshm: [Function (anonymous)],
      rsubm: [Function (anonymous)],
      rsupm: [Function (anonymous)],
      rum: [Function (anonymous)],
      mhpa: [Function (anonymous)],
      mcud1: [Function (anonymous)],
      mcub1: [Function (anonymous)],
      mcuf1: [Function (anonymous)],
      mvpa: [Function (anonymous)],
      mcuu1: [Function (anonymous)],
      porder: [Function (anonymous)],
      mcud: [Function (anonymous)],
      mcub: [Function (anonymous)],
      mcuf: [Function (anonymous)],
      mcuu: [Function (anonymous)],
      scs: [Function (anonymous)],
      smgb: [Function (anonymous)],
      smgbp: [Function (anonymous)],
      smglp: [Function (anonymous)],
      smgrp: [Function (anonymous)],
      smgt: [Function (anonymous)],
      smgtp: [Function (anonymous)],
      sbim: [Function (anonymous)],
      scsd: [Function (anonymous)],
      rbim: [Function (anonymous)],
      rcsd: [Function (anonymous)],
      subcs: [Function (anonymous)],
      supcs: [Function (anonymous)],
      docr: [Function (anonymous)],
      zerom: [Function (anonymous)],
      csnm: [Function (anonymous)],
      minfo: [Function (anonymous)],
      getm: [Function (anonymous)],
      pfxl: [Function (anonymous)],
      devt: [Function (anonymous)],
      csin: [Function (anonymous)],
      s0ds: [Function (anonymous)],
      s1ds: [Function (anonymous)],
      s2ds: [Function (anonymous)],
      s3ds: [Function (anonymous)],
      smglr: [Function (anonymous)],
      smgtb: [Function (anonymous)],
      birep: [Function (anonymous)],
      binel: [Function (anonymous)],
      bicr: [Function (anonymous)],
      colornm: [Function (anonymous)],
      defbi: [Function (anonymous)],
      endbi: [Function (anonymous)],
      setcolor: [Function (anonymous)],
      slines: [Function (anonymous)],
      dispc: [Function (anonymous)],
      smpch: [Function (anonymous)],
      rmpch: [Function (anonymous)],
      smsc: [Function (anonymous)],
      rmsc: [Function (anonymous)],
      pctrm: [Function (anonymous)],
      scesc: [Function (anonymous)],
      scesa: [Function (anonymous)],
      ehhlm: [Function (anonymous)],
      elhlm: [Function (anonymous)],
      elohlm: [Function (anonymous)],
      erhlm: [Function (anonymous)],
      ethlm: [Function (anonymous)],
      evhlm: [Function (anonymous)],
      sgr1: [Function (anonymous)],
      slength: [Function (anonymous)],
      info: [Object],
      all: [Object],
      methods: [Object],
      bools: [Object],
      numbers: [Object],
      strings: [Object],
      features: [Object],
      unicode: true,
      brokenACS: false,
      PCRomSet: false,
      magicCookie: true,
      setbuf: true,
      acscr: [Object],
      _newHandler: [Function: fn],
      isAlt: true,
      cursorHidden: true,
      [Symbol(kCapture)]: false
    },
    tput: Tput {
      options: [Object],
      terminal: 'xterm',
      debug: undefined,
      padding: undefined,
      extended: undefined,
      printf: undefined,
      termcap: undefined,
      error: Error: Terminfo not found.
          at Tput.setup (/home/zmg/Tinker/wiener/node_modules/blessed/lib/tput.js:91:18)
          at new Tput (/home/zmg/Tinker/wiener/node_modules/blessed/lib/tput.js:63:10)
          at Program.setupTput (/home/zmg/Tinker/wiener/node_modules/blessed/lib/program.js:251:26)
          at new Program (/home/zmg/Tinker/wiener/node_modules/blessed/lib/program.js:112:10)
          at Program (/home/zmg/Tinker/wiener/node_modules/blessed/lib/program.js:31:12)
          at new Screen (/home/zmg/Tinker/wiener/node_modules/blessed/lib/widgets/screen.js:49:20)
          at Function.Screen (/home/zmg/Tinker/wiener/node_modules/blessed/lib/widgets/screen.js:36:12)
          at REPL4:1:24
          at Script.runInThisContext (vm.js:134:12)
          at REPLServer.defaultEval (repl.js:566:29),
      terminfoPrefix: undefined,
      terminfoFile: undefined,
      termcapFile: undefined,
      auto_left_margin: false,
      auto_right_margin: true,
      no_esc_ctlc: false,
      ceol_standout_glitch: false,
      eat_newline_glitch: true,
      erase_overstrike: false,
      generic_type: false,
      hard_copy: false,
      has_meta_key: true,
      has_status_line: false,
      insert_null_glitch: false,
      memory_above: false,
      memory_below: false,
      move_insert_mode: true,
      move_standout_mode: true,
      over_strike: false,
      status_line_esc_ok: false,
      dest_tabs_magic_smso: false,
      tilde_glitch: false,
      transparent_underline: false,
      xon_xoff: false,
      needs_xon_xoff: false,
      prtr_silent: true,
      hard_cursor: false,
      non_rev_rmcup: false,
      no_pad_char: true,
      non_dest_scroll_region: false,
      can_change: false,
      back_color_erase: true,
      hue_lightness_saturation: false,
      col_addr_glitch: false,
      cr_cancels_micro_mode: false,
      has_print_wheel: false,
      row_addr_glitch: false,
      semi_auto_right_margin: false,
      cpi_changes_res: false,
      lpi_changes_res: false,
      backspaces_with_bs: true,
      AX: true,
      XT: true,
      columns: 80,
      init_tabs: 8,
      lines: 24,
      lines_of_memory: -1,
      magic_cookie_glitch: -1,
      padding_baud_rate: -1,
      virtual_terminal: -1,
      width_status_line: -1,
      num_labels: -1,
      label_height: -1,
      label_width: -1,
      max_attributes: -1,
      maximum_windows: -1,
      max_colors: 8,
      max_pairs: 64,
      back_tab: [Function (anonymous)],
      bell: [Function (anonymous)],
      carriage_return: [Function (anonymous)],
      change_scroll_region: [Function (anonymous)],
      clear_all_tabs: [Function (anonymous)],
      clear_screen: [Function (anonymous)],
      clr_eol: [Function (anonymous)],
      clr_eos: [Function (anonymous)],
      column_address: [Function (anonymous)],
      cursor_address: [Function (anonymous)],
      cursor_down: [Function (anonymous)],
      cursor_home: [Function (anonymous)],
      cursor_invisible: [Function (anonymous)],
      cursor_left: [Function (anonymous)],
      cursor_normal: [Function (anonymous)],
      cursor_right: [Function (anonymous)],
      cursor_up: [Function (anonymous)],
      cursor_visible: [Function (anonymous)],
      delete_character: [Function (anonymous)],
      delete_line: [Function (anonymous)],
      enter_alt_charset_mode: [Function (anonymous)],
      enter_blink_mode: [Function (anonymous)],
      enter_bold_mode: [Function (anonymous)],
      enter_ca_mode: [Function (anonymous)],
      enter_insert_mode: [Function (anonymous)],
      enter_secure_mode: [Function (anonymous)],
      enter_reverse_mode: [Function (anonymous)],
      enter_standout_mode: [Function (anonymous)],
      enter_underline_mode: [Function (anonymous)],
      erase_chars: [Function (anonymous)],
      exit_alt_charset_mode: [Function (anonymous)],
      exit_attribute_mode: [Function (anonymous)],
      exit_ca_mode: [Function (anonymous)],
      exit_insert_mode: [Function (anonymous)],
      exit_standout_mode: [Function (anonymous)],
      exit_underline_mode: [Function (anonymous)],
      flash_screen: [Function (anonymous)],
      init_2string: [Function (anonymous)],
      insert_line: [Function (anonymous)],
      key_backspace: [Function (anonymous)],
      key_dc: [Function (anonymous)],
      key_down: [Function (anonymous)],
      key_f1: [Function (anonymous)],
      key_f10: [Function (anonymous)],
      key_f2: [Function (anonymous)],
      key_f3: [Function (anonymous)],
      key_f4: [Function (anonymous)],
      key_f5: [Function (anonymous)],
      key_f6: [Function (anonymous)],
      key_f7: [Function (anonymous)],
      key_f8: [Function (anonymous)],
      key_f9: [Function (anonymous)],
      key_home: [Function (anonymous)],
      key_ic: [Function (anonymous)],
      key_left: [Function (anonymous)],
      key_npage: [Function (anonymous)],
      key_ppage: [Function (anonymous)],
      key_right: [Function (anonymous)],
      key_sf: [Function (anonymous)],
      key_sr: [Function (anonymous)],
      key_up: [Function (anonymous)],
      keypad_local: [Function (anonymous)],
      keypad_xmit: [Function (anonymous)],
      meta_off: [Function (anonymous)],
      meta_on: [Function (anonymous)],
      parm_dch: [Function (anonymous)],
      parm_delete_line: [Function (anonymous)],
      parm_down_cursor: [Function (anonymous)],
      parm_ich: [Function (anonymous)],
      parm_index: [Function (anonymous)],
      parm_insert_line: [Function (anonymous)],
      parm_left_cursor: [Function (anonymous)],
      parm_right_cursor: [Function (anonymous)],
      parm_rindex: [Function (anonymous)],
      parm_up_cursor: [Function (anonymous)],
      print_screen: [Function (anonymous)],
      prtr_off: [Function (anonymous)],
      prtr_on: [Function (anonymous)],
      reset_1string: [Function (anonymous)],
      reset_2string: [Function (anonymous)],
      restore_cursor: [Function (anonymous)],
      row_address: [Function (anonymous)],
      save_cursor: [Function (anonymous)],
      scroll_forward: [Function (anonymous)],
      scroll_reverse: [Function (anonymous)],
      set_attributes: [Function (anonymous)],
      set_tab: [Function (anonymous)],
      tab: [Function (anonymous)],
      key_b2: [Function (anonymous)],
      acs_chars: [Function (anonymous)],
      key_btab: [Function (anonymous)],
      enter_am_mode: [Function (anonymous)],
      exit_am_mode: [Function (anonymous)],
      key_end: [Function (anonymous)],
      key_enter: [Function (anonymous)],
      key_sdc: [Function (anonymous)],
      key_send: [Function (anonymous)],
      key_shome: [Function (anonymous)],
      key_sic: [Function (anonymous)],
      key_sleft: [Function (anonymous)],
      key_snext: [Function (anonymous)],
      key_sprevious: [Function (anonymous)],
      key_sright: [Function (anonymous)],
      key_f11: [Function (anonymous)],
      key_f12: [Function (anonymous)],
      key_f13: [Function (anonymous)],
      key_f14: [Function (anonymous)],
      key_f15: [Function (anonymous)],
      key_f16: [Function (anonymous)],
      key_f17: [Function (anonymous)],
      key_f18: [Function (anonymous)],
      key_f19: [Function (anonymous)],
      key_f20: [Function (anonymous)],
      key_f21: [Function (anonymous)],
      key_f22: [Function (anonymous)],
      key_f23: [Function (anonymous)],
      key_f24: [Function (anonymous)],
      key_f25: [Function (anonymous)],
      key_f26: [Function (anonymous)],
      key_f27: [Function (anonymous)],
      key_f28: [Function (anonymous)],
      key_f29: [Function (anonymous)],
      key_f30: [Function (anonymous)],
      key_f31: [Function (anonymous)],
      key_f32: [Function (anonymous)],
      key_f33: [Function (anonymous)],
      key_f34: [Function (anonymous)],
      key_f35: [Function (anonymous)],
      key_f36: [Function (anonymous)],
      key_f37: [Function (anonymous)],
      key_f38: [Function (anonymous)],
      key_f39: [Function (anonymous)],
      key_f40: [Function (anonymous)],
      key_f41: [Function (anonymous)],
      key_f42: [Function (anonymous)],
      key_f43: [Function (anonymous)],
      key_f44: [Function (anonymous)],
      key_f45: [Function (anonymous)],
      key_f46: [Function (anonymous)],
      key_f47: [Function (anonymous)],
      key_f48: [Function (anonymous)],
      key_f49: [Function (anonymous)],
      key_f50: [Function (anonymous)],
      key_f51: [Function (anonymous)],
      key_f52: [Function (anonymous)],
      key_f53: [Function (anonymous)],
      key_f54: [Function (anonymous)],
      key_f55: [Function (anonymous)],
      key_f56: [Function (anonymous)],
      key_f57: [Function (anonymous)],
      key_f58: [Function (anonymous)],
      key_f59: [Function (anonymous)],
      key_f60: [Function (anonymous)],
      key_f61: [Function (anonymous)],
      key_f62: [Function (anonymous)],
      key_f63: [Function (anonymous)],
      clr_bol: [Function (anonymous)],
      user6: [Function (anonymous)],
      user7: [Function (anonymous)],
      user8: [Function (anonymous)],
      user9: [Function (anonymous)],
      orig_pair: [Function (anonymous)],
      set_foreground: [Function (anonymous)],
      set_background: [Function (anonymous)],
      key_mouse: [Function (anonymous)],
      set_a_foreground: [Function (anonymous)],
      set_a_background: [Function (anonymous)],
      memory_lock: [Function (anonymous)],
      memory_unlock: [Function (anonymous)],
      Cr: [Function (anonymous)],
      Cs: [Function (anonymous)],
      E3: [Function (anonymous)],
      Ms: [Function (anonymous)],
      Se: [Function (anonymous)],
      Ss: [Function (anonymous)],
      kDC3: [Function (anonymous)],
      kDC4: [Function (anonymous)],
      kDC5: [Function (anonymous)],
      kDC6: [Function (anonymous)],
      kDC7: [Function (anonymous)],
      kDN: [Function (anonymous)],
      kDN3: [Function (anonymous)],
      kDN4: [Function (anonymous)],
      kDN5: [Function (anonymous)],
      kDN6: [Function (anonymous)],
      kDN7: [Function (anonymous)],
      kEND3: [Function (anonymous)],
      kEND4: [Function (anonymous)],
      kEND5: [Function (anonymous)],
      kEND6: [Function (anonymous)],
      kEND7: [Function (anonymous)],
      kHOM3: [Function (anonymous)],
      kHOM4: [Function (anonymous)],
      kHOM5: [Function (anonymous)],
      kHOM6: [Function (anonymous)],
      kHOM7: [Function (anonymous)],
      kIC3: [Function (anonymous)],
      kIC4: [Function (anonymous)],
      kIC5: [Function (anonymous)],
      kIC6: [Function (anonymous)],
      kIC7: [Function (anonymous)],
      kLFT3: [Function (anonymous)],
      kLFT4: [Function (anonymous)],
      kLFT5: [Function (anonymous)],
      kLFT6: [Function (anonymous)],
      kLFT7: [Function (anonymous)],
      kNXT3: [Function (anonymous)],
      kNXT4: [Function (anonymous)],
      kNXT5: [Function (anonymous)],
      kNXT6: [Function (anonymous)],
      kNXT7: [Function (anonymous)],
      kPRV3: [Function (anonymous)],
      kPRV4: [Function (anonymous)],
      kPRV5: [Function (anonymous)],
      kPRV6: [Function (anonymous)],
      kPRV7: [Function (anonymous)],
      kRIT3: [Function (anonymous)],
      kRIT4: [Function (anonymous)],
      kRIT5: [Function (anonymous)],
      kRIT6: [Function (anonymous)],
      kRIT7: [Function (anonymous)],
      kUP: [Function (anonymous)],
      kUP3: [Function (anonymous)],
      kUP4: [Function (anonymous)],
      kUP5: [Function (anonymous)],
      kUP6: [Function (anonymous)],
      kUP7: [Function (anonymous)],
      ka2: [Function (anonymous)],
      kb1: [Function (anonymous)],
      kb3: [Function (anonymous)],
      kc2: [Function (anonymous)],
      crt_no_scrolling: false,
      no_correctly_working_cr: false,
      gnu_has_meta_key: false,
      linefeed_is_newline: false,
      has_hardware_tabs: false,
      return_does_clr_eol: false,
      no_color_video: -1,
      buffer_capacity: -1,
      dot_vert_spacing: -1,
      dot_horz_spacing: -1,
      max_micro_address: -1,
      max_micro_jump: -1,
      micro_col_size: -1,
      micro_line_size: -1,
      number_of_pins: -1,
      output_res_char: -1,
      output_res_line: -1,
      output_res_horz_inch: -1,
      output_res_vert_inch: -1,
      print_rate: -1,
      wide_char_size: -1,
      buttons: -1,
      bit_image_entwining: -1,
      bit_image_type: -1,
      magic_cookie_glitch_ul: -1,
      carriage_return_delay: -1,
      new_line_delay: -1,
      backspace_delay: -1,
      horizontal_tab_delay: -1,
      number_of_function_keys: -1,
      command_character: [Function (anonymous)],
      cursor_mem_address: [Function (anonymous)],
      cursor_to_ll: [Function (anonymous)],
      dis_status_line: [Function (anonymous)],
      down_half_line: [Function (anonymous)],
      enter_delete_mode: [Function (anonymous)],
      enter_dim_mode: [Function (anonymous)],
      enter_protected_mode: [Function (anonymous)],
      exit_delete_mode: [Function (anonymous)],
      form_feed: [Function (anonymous)],
      from_status_line: [Function (anonymous)],
      init_1string: [Function (anonymous)],
      init_3string: [Function (anonymous)],
      init_file: [Function (anonymous)],
      insert_character: [Function (anonymous)],
      insert_padding: [Function (anonymous)],
      key_catab: [Function (anonymous)],
      key_clear: [Function (anonymous)],
      key_ctab: [Function (anonymous)],
      key_dl: [Function (anonymous)],
      key_eic: [Function (anonymous)],
      key_eol: [Function (anonymous)],
      key_eos: [Function (anonymous)],
      key_f0: [Function (anonymous)],
      key_il: [Function (anonymous)],
      key_ll: [Function (anonymous)],
      key_stab: [Function (anonymous)],
      lab_f0: [Function (anonymous)],
      lab_f1: [Function (anonymous)],
      lab_f10: [Function (anonymous)],
      lab_f2: [Function (anonymous)],
      lab_f3: [Function (anonymous)],
      lab_f4: [Function (anonymous)],
      lab_f5: [Function (anonymous)],
      lab_f6: [Function (anonymous)],
      lab_f7: [Function (anonymous)],
      lab_f8: [Function (anonymous)],
      lab_f9: [Function (anonymous)],
      newline: [Function (anonymous)],
      pad_char: [Function (anonymous)],
      pkey_key: [Function (anonymous)],
      pkey_local: [Function (anonymous)],
      pkey_xmit: [Function (anonymous)],
      repeat_char: [Function (anonymous)],
      reset_3string: [Function (anonymous)],
      reset_file: [Function (anonymous)],
      set_window: [Function (anonymous)],
      to_status_line: [Function (anonymous)],
      underline_char: [Function (anonymous)],
      up_half_line: [Function (anonymous)],
      init_prog: [Function (anonymous)],
      key_a1: [Function (anonymous)],
      key_a3: [Function (anonymous)],
      key_c1: [Function (anonymous)],
      key_c3: [Function (anonymous)],
      prtr_non: [Function (anonymous)],
      char_padding: [Function (anonymous)],
      plab_norm: [Function (anonymous)],
      enter_xon_mode: [Function (anonymous)],
      exit_xon_mode: [Function (anonymous)],
      xon_character: [Function (anonymous)],
      xoff_character: [Function (anonymous)],
      ena_acs: [Function (anonymous)],
      label_on: [Function (anonymous)],
      label_off: [Function (anonymous)],
      key_beg: [Function (anonymous)],
      key_cancel: [Function (anonymous)],
      key_close: [Function (anonymous)],
      key_command: [Function (anonymous)],
      key_copy: [Function (anonymous)],
      key_create: [Function (anonymous)],
      key_exit: [Function (anonymous)],
      key_find: [Function (anonymous)],
      key_help: [Function (anonymous)],
      key_mark: [Function (anonymous)],
      key_message: [Function (anonymous)],
      key_move: [Function (anonymous)],
      key_next: [Function (anonymous)],
      key_open: [Function (anonymous)],
      key_options: [Function (anonymous)],
      key_previous: [Function (anonymous)],
      key_print: [Function (anonymous)],
      key_redo: [Function (anonymous)],
      key_reference: [Function (anonymous)],
      key_refresh: [Function (anonymous)],
      key_replace: [Function (anonymous)],
      key_restart: [Function (anonymous)],
      key_resume: [Function (anonymous)],
      key_save: [Function (anonymous)],
      key_suspend: [Function (anonymous)],
      key_undo: [Function (anonymous)],
      key_sbeg: [Function (anonymous)],
      key_scancel: [Function (anonymous)],
      key_scommand: [Function (anonymous)],
      key_scopy: [Function (anonymous)],
      key_screate: [Function (anonymous)],
      key_sdl: [Function (anonymous)],
      key_select: [Function (anonymous)],
      key_seol: [Function (anonymous)],
      key_sexit: [Function (anonymous)],
      key_sfind: [Function (anonymous)],
      key_shelp: [Function (anonymous)],
      key_smessage: [Function (anonymous)],
      key_smove: [Function (anonymous)],
      key_soptions: [Function (anonymous)],
      key_sprint: [Function (anonymous)],
      key_sredo: [Function (anonymous)],
      key_sreplace: [Function (anonymous)],
      key_srsume: [Function (anonymous)],
      key_ssave: [Function (anonymous)],
      key_ssuspend: [Function (anonymous)],
      key_sundo: [Function (anonymous)],
      req_for_input: [Function (anonymous)],
      clear_margins: [Function (anonymous)],
      set_left_margin: [Function (anonymous)],
      set_right_margin: [Function (anonymous)],
      label_format: [Function (anonymous)],
      set_clock: [Function (anonymous)],
      display_clock: [Function (anonymous)],
      remove_clock: [Function (anonymous)],
      create_window: [Function (anonymous)],
      goto_window: [Function (anonymous)],
      hangup: [Function (anonymous)],
      dial_phone: [Function (anonymous)],
      quick_dial: [Function (anonymous)],
      tone: [Function (anonymous)],
      pulse: [Function (anonymous)],
      flash_hook: [Function (anonymous)],
      fixed_pause: [Function (anonymous)],
      wait_tone: [Function (anonymous)],
      user0: [Function (anonymous)],
      user1: [Function (anonymous)],
      user2: [Function (anonymous)],
      user3: [Function (anonymous)],
      user4: [Function (anonymous)],
      user5: [Function (anonymous)],
      orig_colors: [Function (anonymous)],
      initialize_color: [Function (anonymous)],
      initialize_pair: [Function (anonymous)],
      set_color_pair: [Function (anonymous)],
      change_char_pitch: [Function (anonymous)],
      change_line_pitch: [Function (anonymous)],
      change_res_horz: [Function (anonymous)],
      change_res_vert: [Function (anonymous)],
      define_char: [Function (anonymous)],
      enter_doublewide_mode: [Function (anonymous)],
      enter_draft_quality: [Function (anonymous)],
      enter_italics_mode: [Function (anonymous)],
      enter_leftward_mode: [Function (anonymous)],
      enter_micro_mode: [Function (anonymous)],
      enter_near_letter_quality: [Function (anonymous)],
      enter_normal_quality: [Function (anonymous)],
      enter_shadow_mode: [Function (anonymous)],
      enter_subscript_mode: [Function (anonymous)],
      enter_superscript_mode: [Function (anonymous)],
      enter_upward_mode: [Function (anonymous)],
      exit_doublewide_mode: [Function (anonymous)],
      exit_italics_mode: [Function (anonymous)],
      exit_leftward_mode: [Function (anonymous)],
      exit_micro_mode: [Function (anonymous)],
      exit_shadow_mode: [Function (anonymous)],
      exit_subscript_mode: [Function (anonymous)],
      exit_superscript_mode: [Function (anonymous)],
      exit_upward_mode: [Function (anonymous)],
      micro_column_address: [Function (anonymous)],
      micro_down: [Function (anonymous)],
      micro_left: [Function (anonymous)],
      micro_right: [Function (anonymous)],
      micro_row_address: [Function (anonymous)],
      micro_up: [Function (anonymous)],
      order_of_pins: [Function (anonymous)],
      parm_down_micro: [Function (anonymous)],
      parm_left_micro: [Function (anonymous)],
      parm_right_micro: [Function (anonymous)],
      parm_up_micro: [Function (anonymous)],
      select_char_set: [Function (anonymous)],
      set_bottom_margin: [Function (anonymous)],
      set_bottom_margin_parm: [Function (anonymous)],
      set_left_margin_parm: [Function (anonymous)],
      set_right_margin_parm: [Function (anonymous)],
      set_top_margin: [Function (anonymous)],
      set_top_margin_parm: [Function (anonymous)],
      start_bit_image: [Function (anonymous)],
      start_char_set_def: [Function (anonymous)],
      stop_bit_image: [Function (anonymous)],
      stop_char_set_def: [Function (anonymous)],
      subscript_characters: [Function (anonymous)],
      superscript_characters: [Function (anonymous)],
      these_cause_cr: [Function (anonymous)],
      zero_motion: [Function (anonymous)],
      char_set_names: [Function (anonymous)],
      mouse_info: [Function (anonymous)],
      req_mouse_pos: [Function (anonymous)],
      get_mouse: [Function (anonymous)],
      pkey_plab: [Function (anonymous)],
      device_type: [Function (anonymous)],
      code_set_init: [Function (anonymous)],
      set0_des_seq: [Function (anonymous)],
      set1_des_seq: [Function (anonymous)],
      set2_des_seq: [Function (anonymous)],
      set3_des_seq: [Function (anonymous)],
      set_lr_margin: [Function (anonymous)],
      set_tb_margin: [Function (anonymous)],
      bit_image_repeat: [Function (anonymous)],
      bit_image_newline: [Function (anonymous)],
      bit_image_carriage_return: [Function (anonymous)],
      color_names: [Function (anonymous)],
      define_bit_image_region: [Function (anonymous)],
      end_bit_image_region: [Function (anonymous)],
      set_color_band: [Function (anonymous)],
      set_page_length: [Function (anonymous)],
      display_pc_char: [Function (anonymous)],
      enter_pc_charset_mode: [Function (anonymous)],
      exit_pc_charset_mode: [Function (anonymous)],
      enter_scancode_mode: [Function (anonymous)],
      exit_scancode_mode: [Function (anonymous)],
      pc_term_options: [Function (anonymous)],
      scancode_escape: [Function (anonymous)],
      alt_scancode_esc: [Function (anonymous)],
      enter_horizontal_hl_mode: [Function (anonymous)],
      enter_left_hl_mode: [Function (anonymous)],
      enter_low_hl_mode: [Function (anonymous)],
      enter_right_hl_mode: [Function (anonymous)],
      enter_top_hl_mode: [Function (anonymous)],
      enter_vertical_hl_mode: [Function (anonymous)],
      set_a_attributes: [Function (anonymous)],
      set_pglen_inch: [Function (anonymous)],
      termcap_init2: [Function (anonymous)],
      termcap_reset: [Function (anonymous)],
      linefeed_if_not_lf: [Function (anonymous)],
      backspace_if_not_bs: [Function (anonymous)],
      other_non_function_keys: [Function (anonymous)],
      arrow_key_map: [Function (anonymous)],
      acs_ulcorner: [Function (anonymous)],
      acs_llcorner: [Function (anonymous)],
      acs_urcorner: [Function (anonymous)],
      acs_lrcorner: [Function (anonymous)],
      acs_ltee: [Function (anonymous)],
      acs_rtee: [Function (anonymous)],
      acs_btee: [Function (anonymous)],
      acs_ttee: [Function (anonymous)],
      acs_hline: [Function (anonymous)],
      acs_vline: [Function (anonymous)],
      acs_plus: [Function (anonymous)],
      box_chars_1: [Function (anonymous)],
      bw: false,
      am: true,
      xsb: false,
      beehive_glitch: false,
      xhp: false,
      xenl: true,
      eo: false,
      gn: false,
      hc: false,
      km: true,
      hs: false,
      in: false,
      da: false,
      db: false,
      mir: true,
      msgr: true,
      os: false,
      eslok: false,
      xt: false,
      teleray_glitch: false,
      hz: false,
      ul: false,
      xon: false,
      nxon: false,
      mc5i: true,
      chts: false,
      nrrmc: false,
      npc: true,
      ndscr: false,
      ccc: false,
      bce: true,
      hls: false,
      xhpa: false,
      crxm: false,
      daisy: false,
      xvpa: false,
      sam: false,
      cpix: false,
      lpix: false,
      cols: 80,
      it: 8,
      lm: -1,
      xmc: -1,
      pb: -1,
      vt: -1,
      wsl: -1,
      nlab: -1,
      lh: -1,
      lw: -1,
      ma: -1,
      wnum: -1,
      colors: 8,
      pairs: 64,
      cbt: [Function (anonymous)],
      bel: [Function (anonymous)],
      cr: [Function (anonymous)],
      csr: [Function (anonymous)],
      tbc: [Function (anonymous)],
      clear: [Function (anonymous)],
      el: [Function (anonymous)],
      ed: [Function (anonymous)],
      hpa: [Function (anonymous)],
      cup: [Function (anonymous)],
      cud1: [Function (anonymous)],
      home: [Function (anonymous)],
      civis: [Function (anonymous)],
      cub1: [Function (anonymous)],
      cnorm: [Function (anonymous)],
      cuf1: [Function (anonymous)],
      cuu1: [Function (anonymous)],
      cvvis: [Function (anonymous)],
      dch1: [Function (anonymous)],
      dl1: [Function (anonymous)],
      smacs: [Function (anonymous)],
      blink: [Function (anonymous)],
      bold: [Function (anonymous)],
      smcup: [Function (anonymous)],
      smir: [Function (anonymous)],
      invis: [Function (anonymous)],
      rev: [Function (anonymous)],
      smso: [Function (anonymous)],
      smul: [Function (anonymous)],
      ech: [Function (anonymous)],
      rmacs: [Function (anonymous)],
      sgr0: [Function (anonymous)],
      rmcup: [Function (anonymous)],
      rmir: [Function (anonymous)],
      rmso: [Function (anonymous)],
      rmul: [Function (anonymous)],
      flash: [Function (anonymous)],
      is2: [Function (anonymous)],
      il1: [Function (anonymous)],
      kbs: [Function (anonymous)],
      kdch1: [Function (anonymous)],
      kcud1: [Function (anonymous)],
      kf1: [Function (anonymous)],
      kf10: [Function (anonymous)],
      kf2: [Function (anonymous)],
      kf3: [Function (anonymous)],
      kf4: [Function (anonymous)],
      kf5: [Function (anonymous)],
      kf6: [Function (anonymous)],
      kf7: [Function (anonymous)],
      kf8: [Function (anonymous)],
      kf9: [Function (anonymous)],
      khome: [Function (anonymous)],
      kich1: [Function (anonymous)],
      kcub1: [Function (anonymous)],
      knp: [Function (anonymous)],
      kpp: [Function (anonymous)],
      kcuf1: [Function (anonymous)],
      kind: [Function (anonymous)],
      kri: [Function (anonymous)],
      kcuu1: [Function (anonymous)],
      rmkx: [Function (anonymous)],
      smkx: [Function (anonymous)],
      rmm: [Function (anonymous)],
      smm: [Function (anonymous)],
      dch: [Function (anonymous)],
      dl: [Function (anonymous)],
      cud: [Function (anonymous)],
      ich: [Function (anonymous)],
      indn: [Function (anonymous)],
      il: [Function (anonymous)],
      cub: [Function (anonymous)],
      cuf: [Function (anonymous)],
      rin: [Function (anonymous)],
      cuu: [Function (anonymous)],
      mc0: [Function (anonymous)],
      mc4: [Function (anonymous)],
      mc5: [Function (anonymous)],
      rs1: [Function (anonymous)],
      rs2: [Function (anonymous)],
      rc: [Function (anonymous)],
      vpa: [Function (anonymous)],
      sc: [Function (anonymous)],
      ind: [Function (anonymous)],
      ri: [Function (anonymous)],
      sgr: [Function (anonymous)],
      hts: [Function (anonymous)],
      ht: [Function (anonymous)],
      kb2: [Function (anonymous)],
      acsc: [Object],
      kcbt: [Function (anonymous)],
      smam: [Function (anonymous)],
      rmam: [Function (anonymous)],
      kend: [Function (anonymous)],
      kent: [Function (anonymous)],
      kDC: [Function (anonymous)],
      kEND: [Function (anonymous)],
      kHOM: [Function (anonymous)],
      kIC: [Function (anonymous)],
      kLFT: [Function (anonymous)],
      kNXT: [Function (anonymous)],
      kPRV: [Function (anonymous)],
      kRIT: [Function (anonymous)],
      kf11: [Function (anonymous)],
      kf12: [Function (anonymous)],
      kf13: [Function (anonymous)],
      kf14: [Function (anonymous)],
      kf15: [Function (anonymous)],
      kf16: [Function (anonymous)],
      kf17: [Function (anonymous)],
      kf18: [Function (anonymous)],
      kf19: [Function (anonymous)],
      kf20: [Function (anonymous)],
      kf21: [Function (anonymous)],
      kf22: [Function (anonymous)],
      kf23: [Function (anonymous)],
      kf24: [Function (anonymous)],
      kf25: [Function (anonymous)],
      kf26: [Function (anonymous)],
      kf27: [Function (anonymous)],
      kf28: [Function (anonymous)],
      kf29: [Function (anonymous)],
      kf30: [Function (anonymous)],
      kf31: [Function (anonymous)],
      kf32: [Function (anonymous)],
      kf33: [Function (anonymous)],
      kf34: [Function (anonymous)],
      kf35: [Function (anonymous)],
      kf36: [Function (anonymous)],
      kf37: [Function (anonymous)],
      kf38: [Function (anonymous)],
      kf39: [Function (anonymous)],
      kf40: [Function (anonymous)],
      kf41: [Function (anonymous)],
      kf42: [Function (anonymous)],
      kf43: [Function (anonymous)],
      kf44: [Function (anonymous)],
      kf45: [Function (anonymous)],
      kf46: [Function (anonymous)],
      kf47: [Function (anonymous)],
      kf48: [Function (anonymous)],
      kf49: [Function (anonymous)],
      kf50: [Function (anonymous)],
      kf51: [Function (anonymous)],
      kf52: [Function (anonymous)],
      kf53: [Function (anonymous)],
      kf54: [Function (anonymous)],
      kf55: [Function (anonymous)],
      kf56: [Function (anonymous)],
      kf57: [Function (anonymous)],
      kf58: [Function (anonymous)],
      kf59: [Function (anonymous)],
      kf60: [Function (anonymous)],
      kf61: [Function (anonymous)],
      kf62: [Function (anonymous)],
      kf63: [Function (anonymous)],
      el1: [Function (anonymous)],
      u6: [Function (anonymous)],
      u7: [Function (anonymous)],
      u8: [Function (anonymous)],
      u9: [Function (anonymous)],
      op: [Function (anonymous)],
      setf: [Function (anonymous)],
      setb: [Function (anonymous)],
      kmous: [Function (anonymous)],
      setaf: [Function (anonymous)],
      setab: [Function (anonymous)],
      ncv: -1,
      bufsz: -1,
      spinv: -1,
      spinh: -1,
      maddr: -1,
      mjump: -1,
      mcs: -1,
      micro_char_size: -1,
      mls: -1,
      npins: -1,
      orc: -1,
      orl: -1,
      orhi: -1,
      orvi: -1,
      cps: -1,
      widcs: -1,
      btns: -1,
      bitwin: -1,
      bitype: -1,
      cmdch: [Function (anonymous)],
      mrcup: [Function (anonymous)],
      ll: [Function (anonymous)],
      dsl: [Function (anonymous)],
      hd: [Function (anonymous)],
      smdc: [Function (anonymous)],
      dim: [Function (anonymous)],
      prot: [Function (anonymous)],
      rmdc: [Function (anonymous)],
      ff: [Function (anonymous)],
      fsl: [Function (anonymous)],
      is1: [Function (anonymous)],
      is3: [Function (anonymous)],
      if: [Function (anonymous)],
      ich1: [Function (anonymous)],
      ip: [Function (anonymous)],
      ktbc: [Function (anonymous)],
      kclr: [Function (anonymous)],
      kctab: [Function (anonymous)],
      kdl1: [Function (anonymous)],
      krmir: [Function (anonymous)],
      kel: [Function (anonymous)],
      ked: [Function (anonymous)],
      kf0: [Function (anonymous)],
      kil1: [Function (anonymous)],
      kll: [Function (anonymous)],
      khts: [Function (anonymous)],
      lf0: [Function (anonymous)],
      lf1: [Function (anonymous)],
      lf10: [Function (anonymous)],
      lf2: [Function (anonymous)],
      lf3: [Function (anonymous)],
      lf4: [Function (anonymous)],
      lf5: [Function (anonymous)],
      lf6: [Function (anonymous)],
      lf7: [Function (anonymous)],
      lf8: [Function (anonymous)],
      lf9: [Function (anonymous)],
      nel: [Function (anonymous)],
      pad: [Function (anonymous)],
      pfkey: [Function (anonymous)],
      pfloc: [Function (anonymous)],
      pfx: [Function (anonymous)],
      rep: [Function (anonymous)],
      rs3: [Function (anonymous)],
      rf: [Function (anonymous)],
      wind: [Function (anonymous)],
      tsl: [Function (anonymous)],
      uc: [Function (anonymous)],
      hu: [Function (anonymous)],
      iprog: [Function (anonymous)],
      ka1: [Function (anonymous)],
      ka3: [Function (anonymous)],
      kc1: [Function (anonymous)],
      kc3: [Function (anonymous)],
      mc5p: [Function (anonymous)],
      rmp: [Function (anonymous)],
      pln: [Function (anonymous)],
      smxon: [Function (anonymous)],
      rmxon: [Function (anonymous)],
      xonc: [Function (anonymous)],
      xoffc: [Function (anonymous)],
      enacs: [Function (anonymous)],
      smln: [Function (anonymous)],
      rmln: [Function (anonymous)],
      kbeg: [Function (anonymous)],
      kcan: [Function (anonymous)],
      kclo: [Function (anonymous)],
      kcmd: [Function (anonymous)],
      kcpy: [Function (anonymous)],
      kcrt: [Function (anonymous)],
      kext: [Function (anonymous)],
      kfnd: [Function (anonymous)],
      khlp: [Function (anonymous)],
      kmrk: [Function (anonymous)],
      kmsg: [Function (anonymous)],
      kmov: [Function (anonymous)],
      knxt: [Function (anonymous)],
      kopn: [Function (anonymous)],
      kopt: [Function (anonymous)],
      kprv: [Function (anonymous)],
      kprt: [Function (anonymous)],
      krdo: [Function (anonymous)],
      kref: [Function (anonymous)],
      krfr: [Function (anonymous)],
      krpl: [Function (anonymous)],
      krst: [Function (anonymous)],
      kres: [Function (anonymous)],
      ksav: [Function (anonymous)],
      kspd: [Function (anonymous)],
      kund: [Function (anonymous)],
      kBEG: [Function (anonymous)],
      kCAN: [Function (anonymous)],
      kCMD: [Function (anonymous)],
      kCPY: [Function (anonymous)],
      kCRT: [Function (anonymous)],
      kDL: [Function (anonymous)],
      kslt: [Function (anonymous)],
      kEOL: [Function (anonymous)],
      kEXT: [Function (anonymous)],
      kFND: [Function (anonymous)],
      kHLP: [Function (anonymous)],
      kMSG: [Function (anonymous)],
      kMOV: [Function (anonymous)],
      kOPT: [Function (anonymous)],
      kPRT: [Function (anonymous)],
      kRDO: [Function (anonymous)],
      kRPL: [Function (anonymous)],
      kRES: [Function (anonymous)],
      kSAV: [Function (anonymous)],
      kSPD: [Function (anonymous)],
      kUND: [Function (anonymous)],
      rfi: [Function (anonymous)],
      mgc: [Function (anonymous)],
      smgl: [Function (anonymous)],
      smgr: [Function (anonymous)],
      fln: [Function (anonymous)],
      sclk: [Function (anonymous)],
      dclk: [Function (anonymous)],
      rmclk: [Function (anonymous)],
      cwin: [Function (anonymous)],
      wingo: [Function (anonymous)],
      hup: [Function (anonymous)],
      dial: [Function (anonymous)],
      qdial: [Function (anonymous)],
      hook: [Function (anonymous)],
      pause: [Function (anonymous)],
      wait: [Function (anonymous)],
      u0: [Function (anonymous)],
      u1: [Function (anonymous)],
      u2: [Function (anonymous)],
      u3: [Function (anonymous)],
      u4: [Function (anonymous)],
      u5: [Function (anonymous)],
      oc: [Function (anonymous)],
      initc: [Function (anonymous)],
      initp: [Function (anonymous)],
      scp: [Function (anonymous)],
      cpi: [Function (anonymous)],
      lpi: [Function (anonymous)],
      chr: [Function (anonymous)],
      cvr: [Function (anonymous)],
      defc: [Function (anonymous)],
      swidm: [Function (anonymous)],
      sdrfq: [Function (anonymous)],
      sitm: [Function (anonymous)],
      slm: [Function (anonymous)],
      smicm: [Function (anonymous)],
      snlq: [Function (anonymous)],
      snrmq: [Function (anonymous)],
      sshm: [Function (anonymous)],
      ssubm: [Function (anonymous)],
      ssupm: [Function (anonymous)],
      sum: [Function (anonymous)],
      rwidm: [Function (anonymous)],
      ritm: [Function (anonymous)],
      rlm: [Function (anonymous)],
      rmicm: [Function (anonymous)],
      rshm: [Function (anonymous)],
      rsubm: [Function (anonymous)],
      rsupm: [Function (anonymous)],
      rum: [Function (anonymous)],
      mhpa: [Function (anonymous)],
      mcud1: [Function (anonymous)],
      mcub1: [Function (anonymous)],
      mcuf1: [Function (anonymous)],
      mvpa: [Function (anonymous)],
      mcuu1: [Function (anonymous)],
      porder: [Function (anonymous)],
      mcud: [Function (anonymous)],
      mcub: [Function (anonymous)],
      mcuf: [Function (anonymous)],
      mcuu: [Function (anonymous)],
      scs: [Function (anonymous)],
      smgb: [Function (anonymous)],
      smgbp: [Function (anonymous)],
      smglp: [Function (anonymous)],
      smgrp: [Function (anonymous)],
      smgt: [Function (anonymous)],
      smgtp: [Function (anonymous)],
      sbim: [Function (anonymous)],
      scsd: [Function (anonymous)],
      rbim: [Function (anonymous)],
      rcsd: [Function (anonymous)],
      subcs: [Function (anonymous)],
      supcs: [Function (anonymous)],
      docr: [Function (anonymous)],
      zerom: [Function (anonymous)],
      csnm: [Function (anonymous)],
      minfo: [Function (anonymous)],
      reqmp: [Function (anonymous)],
      getm: [Function (anonymous)],
      pfxl: [Function (anonymous)],
      devt: [Function (anonymous)],
      csin: [Function (anonymous)],
      s0ds: [Function (anonymous)],
      s1ds: [Function (anonymous)],
      s2ds: [Function (anonymous)],
      s3ds: [Function (anonymous)],
      smglr: [Function (anonymous)],
      smgtb: [Function (anonymous)],
      birep: [Function (anonymous)],
      binel: [Function (anonymous)],
      bicr: [Function (anonymous)],
      colornm: [Function (anonymous)],
      defbi: [Function (anonymous)],
      endbi: [Function (anonymous)],
      setcolor: [Function (anonymous)],
      slines: [Function (anonymous)],
      dispc: [Function (anonymous)],
      smpch: [Function (anonymous)],
      rmpch: [Function (anonymous)],
      smsc: [Function (anonymous)],
      rmsc: [Function (anonymous)],
      pctrm: [Function (anonymous)],
      scesc: [Function (anonymous)],
      scesa: [Function (anonymous)],
      ehhlm: [Function (anonymous)],
      elhlm: [Function (anonymous)],
      elohlm: [Function (anonymous)],
      erhlm: [Function (anonymous)],
      ethlm: [Function (anonymous)],
      evhlm: [Function (anonymous)],
      sgr1: [Function (anonymous)],
      slength: [Function (anonymous)],
      info: [Object],
      all: [Object],
      methods: [Object],
      bools: [Object],
      numbers: [Object],
      strings: [Object],
      features: [Object],
      unicode: true,
      brokenACS: false,
      PCRomSet: false,
      magicCookie: true,
      setbuf: true,
      acscr: [Object]
    },
    _events: { newListener: [Function: fn] },
    options: { smartCSR: true, cursor: [Object] },
    screen: [Circular *1],
    parent: null,
    children: [],
    data: {},
    _: {},
    '$': {},
    uid: 0,
    autoPadding: true,
    tabc: '    ',
    dockBorders: undefined,
    ignoreLocked: [],
    _unicode: true,
    fullUnicode: undefined,
    dattr: 262143,
    renders: 1,
    rleft: 0,
    aleft: 0,
    left: 0,
    rright: 0,
    aright: 0,
    right: 0,
    rtop: 0,
    atop: 0,
    top: 0,
    rbottom: 0,
    abottom: 0,
    bottom: 0,
    position: {
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      height: [Getter],
      width: [Getter]
    },
    ileft: 0,
    itop: 0,
    iright: 0,
    ibottom: 0,
    iheight: 0,
    iwidth: 0,
    padding: { left: 0, top: 0, right: 0, bottom: 0 },
    hover: null,
    history: [],
    clickable: [],
    keyable: [ [Circular *2] ],
    grabKeys: false,
    lockKeys: false,
    _buf: '',
    _ci: -1,
    cursor: {
      artificial: false,
      shape: 'block',
      blink: false,
      color: null,
      _set: false,
      _state: 1,
      _hidden: true
    },
    _maxListeners: Infinity,
    lines: [
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array]
    ],
    olines: [
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array], [Array], [Array], [Array], [Array],
      [Array]
    ],
    _borderStops: {},
    _listenedKeys: true
  },
  parent: null,
  children: [],
  data: {},
  _: {},
  '$': {},
  uid: 1,
  index: -1,
  detached: true,
  name: undefined,
  position: {
    left: undefined,
    right: undefined,
    top: undefined,
    bottom: undefined,
    width: undefined,
    height: undefined
  },
  noOverflow: undefined,
  dockBorders: undefined,
  shadow: undefined,
  style: {
    fg: undefined,
    bg: undefined,
    bold: undefined,
    underline: undefined,
    blink: undefined,
    inverse: undefined,
    invisible: undefined,
    transparent: undefined
  },
  hidden: false,
  fixed: undefined,
  align: 'left',
  valign: 'top',
  wrap: true,
  shrink: undefined,
  ch: ' ',
  padding: { left: 0, top: 0, right: 0, bottom: 0 },
  border: undefined,
  parseTags: undefined,
  content: '',
  keyable: true
}
undefined
> screen.destroy()
undefined
> zmg@zmg-ConceptD:~/Tinker/wiener$
